from tkinter import *
from tkinter import ttk
import tkinter.font
from math import ceil

# --noconsole : 콘솔화면 없이

# ================== 일반품목 =======================
# { cost[가격] + [가격의10% = 검수비] + [가격의15% = 마진] + [EMS] + 35 } * 195[환율]
def f1_1_alert(event=None):
    cost = int(f1_1_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f1_1_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000
    result_coma = "{:,}".format(result)
    f1_1_lab_cost_ed.config(text=cost_coma)
    f1_1_lab_result.config(text=result_coma)
    f1_1_ent_cost.delete(0, len(f1_1_ent_cost.get()))


def f1_2_alert(event=None):
    cost = int(f1_2_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f1_2_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000
    result_coma = "{:,}".format(result)
    f1_2_lab_cost_ed.config(text=cost_coma)
    f1_2_lab_result.config(text=result_coma)
    f1_2_ent_cost.delete(0, len(f1_2_ent_cost.get()))


def f1_3_alert(event=None):
    cost = int(f1_3_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f1_3_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000
    result_coma = "{:,}".format(result)
    f1_3_lab_cost_ed.config(text=cost_coma)
    f1_3_lab_result.config(text=result_coma)
    f1_3_ent_cost.delete(0, len(f1_3_ent_cost.get()))


def f1_4_alert(event=None):
    cost = int(f1_4_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f1_4_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000
    result_coma = "{:,}".format(result)
    f1_4_lab_cost_ed.config(text=cost_coma)
    f1_4_lab_result.config(text=result_coma)
    f1_4_ent_cost.delete(0, len(f1_4_ent_cost.get()))


def f1_5_alert(event=None):
    cost = int(f1_5_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f1_5_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000
    result_coma = "{:,}".format(result)
    f1_5_lab_cost_ed.config(text=cost_coma)
    f1_5_lab_result.config(text=result_coma)
    f1_5_ent_cost.delete(0, len(f1_5_ent_cost.get()))


def f1_6_alert(event=None):
    cost = int(f1_6_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f1_6_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000
    result_coma = "{:,}".format(result)
    f1_6_lab_cost_ed.config(text=cost_coma)
    f1_6_lab_result.config(text=result_coma)
    f1_6_ent_cost.delete(0, len(f1_6_ent_cost.get()))

# ================== 고가품목 =======================
# { cost[가격] + [가격의10% = 검수비] + [가격의15% = 마진] + [EMS] + 35 } * 185[환율]
def f2_1_alert(event=None):
    cost = int(f2_1_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f2_1_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000
    result_coma = "{:,}".format(result)
    f2_1_lab_cost_ed.config(text=cost_coma)
    f2_1_lab_result.config(text=result_coma)
    f2_1_ent_cost.delete(0, len(f2_1_ent_cost.get()))


def f2_2_alert(event=None):
    cost = int(f2_2_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f2_2_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000
    result_coma = "{:,}".format(result)
    f2_2_lab_cost_ed.config(text=cost_coma)
    f2_2_lab_result.config(text=result_coma)
    f2_2_ent_cost.delete(0, len(f2_2_ent_cost.get()))


def f2_3_alert(event=None):
    cost = int(f2_3_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f2_3_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000
    result_coma = "{:,}".format(result)
    f2_3_lab_cost_ed.config(text=cost_coma)
    f2_3_lab_result.config(text=result_coma)
    f2_3_ent_cost.delete(0, len(f2_3_ent_cost.get()))

# ================== 겨울패딩 =======================
# { cost[가격] + [가격의10% = 검수비] + [가격의15% = 마진] + [EMS] + 35 } * 195[환율]
def f3_1_alert(event=None):
    cost = int(f3_1_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f3_1_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000
    result_coma = "{:,}".format(result)
    f3_1_lab_cost_ed.config(text=cost_coma)
    f3_1_lab_result.config(text=result_coma)
    f3_1_ent_cost.delete(0, len(f3_1_ent_cost.get()))


def f3_2_alert(event=None):
    cost = int(f3_2_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f3_2_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000 + 30000
    result_coma = "{:,}".format(result)
    f3_2_lab_cost_ed.config(text=cost_coma)
    f3_2_lab_result.config(text=result_coma)
    f3_2_ent_cost.delete(0, len(f3_2_ent_cost.get()))


def f3_3_alert(event=None):
    cost = int(f3_3_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f3_3_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000 + 30000
    result_coma = "{:,}".format(result)
    f3_3_lab_cost_ed.config(text=cost_coma)
    f3_3_lab_result.config(text=result_coma)
    f3_3_ent_cost.delete(0, len(f3_3_ent_cost.get()))


def f3_4_alert(event=None):
    cost = int(f3_4_ent_cost.get())
    cost_coma = "{:,}".format(cost)
    EMS = int(f3_4_ent_EMS.get())
    result = (ceil(((cost * 1.25) + EMS + 35) * 0.195)) * 1000 + 30000
    result_coma = "{:,}".format(result)
    f3_4_lab_cost_ed.config(text=cost_coma)
    f3_4_lab_result.config(text=result_coma)
    f3_4_ent_cost.delete(0, len(f3_4_ent_cost.get()))



def f4_memo_write():
    f = open("data.txt", "w")
    f.write(f4_memo_text_1.get(1.0, END))
    f.close()

window = Tk()
window.geometry("800x950+0+0")
window.title("도매 단가 계산기 v1.0 (2022 VER)")
window.option_add("*Font", "맑은고딕 12")
window.configure(bg="white")

frame1 = LabelFrame(window, text="일반품목", bg="white")
frame1.place(x=10, y=20, width=750, height=220)

f1_1_lab_cost = Label(frame1, bg="white", text="Cost :      ")
f1_1_lab_cost.grid(row=0, column=0, padx="10", pady="5")
f1_1_ent_cost = Entry(frame1, width=7)
f1_1_ent_cost.bind("<Return>", f1_1_alert)
f1_1_ent_cost.grid(row=0, column=1, padx="10")
f1_1_lab_cost_ed = Label(frame1, width=7, bg="gray", anchor="w")
f1_1_lab_cost_ed.grid(row=0, column=2, padx="10")
f1_1_lab_slash_1 = Label(frame1, bg="white", text="/")
f1_1_lab_slash_1.grid(row=0, column=3, padx="10")
f1_1_lab_EMS = Label(frame1, bg="white", text="EMS :")
f1_1_lab_EMS.grid(row=0, column=4, padx="10")
f1_1_ent_EMS = Entry(frame1, width=5)
f1_1_ent_EMS.insert(0, "130")
f1_1_ent_EMS.grid(row=0, column=5, padx="10")
f1_1_lab_slash_2 = Label(frame1, bg="white", text="/")
f1_1_lab_slash_2.grid(row=0, column=6, padx="10")
f1_1_btn_result = Button(frame1, text="합계", command=f1_1_alert)
f1_1_btn_result.grid(row=0, column=7, padx="10")
f1_1_lab_result = Label(frame1, width=20, anchor="w")
f1_1_lab_result.grid(row=0, column=8, padx="10")

f1_2_lab_cost = Label(frame1, bg="white", text="Cost :      ")
f1_2_lab_cost.grid(row=1, column=0, padx="10", pady="5")
f1_2_ent_cost = Entry(frame1, width=7)
f1_2_ent_cost.bind("<Return>", f1_2_alert)
f1_2_ent_cost.grid(row=1, column=1, padx="10")
f1_2_lab_cost_ed = Label(frame1, width=7, bg="gray", anchor="w")
f1_2_lab_cost_ed.grid(row=1, column=2, padx="10")
f1_2_lab_slash_1 = Label(frame1, bg="white", text="/")
f1_2_lab_slash_1.grid(row=1, column=3, padx="10")
f1_2_lab_EMS = Label(frame1, bg="white", text="EMS :")
f1_2_lab_EMS.grid(row=1, column=4, padx="10")
f1_2_ent_EMS = Entry(frame1, width=5)
f1_2_ent_EMS.insert(0, "150")
f1_2_ent_EMS.grid(row=1, column=5, padx="10")
f1_2_lab_slash_2 = Label(frame1, bg="white", text="/")
f1_2_lab_slash_2.grid(row=1, column=6, padx="10")
f1_2_btn_result = Button(frame1, text="합계", command=f1_2_alert)
f1_2_btn_result.grid(row=1, column=7, padx="10")
f1_2_lab_result = Label(frame1, width=20, anchor="w")
f1_2_lab_result.grid(row=1, column=8, padx="10")

f1_3_lab_cost = Label(frame1, bg="white", text="Cost :      ")
f1_3_lab_cost.grid(row=2, column=0, padx="10", pady="5")
f1_3_ent_cost = Entry(frame1, width=7)
f1_3_ent_cost.bind("<Return>", f1_3_alert)
f1_3_ent_cost.grid(row=2, column=1, padx="10")
f1_3_lab_cost_ed = Label(frame1, width=7, bg="gray", anchor="w")
f1_3_lab_cost_ed.grid(row=2, column=2, padx="10")
f1_3_lab_slash_1 = Label(frame1, bg="white", text="/")
f1_3_lab_slash_1.grid(row=2, column=3, padx="10")
f1_3_lab_EMS = Label(frame1, bg="white", text="EMS :")
f1_3_lab_EMS.grid(row=2, column=4, padx="10")
f1_3_ent_EMS = Entry(frame1, width=5)
f1_3_ent_EMS.insert(0, "180")
f1_3_ent_EMS.grid(row=2, column=5, padx="10")
f1_3_lab_slash_2 = Label(frame1, bg="white", text="/")
f1_3_lab_slash_2.grid(row=2, column=6, padx="10")
f1_3_btn_result = Button(frame1, text="합계", command=f1_3_alert)
f1_3_btn_result.grid(row=2, column=7, padx="10")
f1_3_lab_result = Label(frame1, width=20, anchor="w")
f1_3_lab_result.grid(row=2, column=8, padx="10")

f1_4_lab_cost = Label(frame1, bg="white", text="Cost :      ")
f1_4_lab_cost.grid(row=3, column=0, padx="10", pady="5")
f1_4_ent_cost = Entry(frame1, width=7)
f1_4_ent_cost.bind("<Return>", f1_4_alert)
f1_4_ent_cost.grid(row=3, column=1, padx="10")
f1_4_lab_cost_ed = Label(frame1, width=7, bg="gray", anchor="w")
f1_4_lab_cost_ed.grid(row=3, column=2, padx="10")
f1_4_lab_slash_1 = Label(frame1, bg="white", text="/")
f1_4_lab_slash_1.grid(row=3, column=3, padx="10")
f1_4_lab_EMS = Label(frame1, bg="white", text="EMS :")
f1_4_lab_EMS.grid(row=3, column=4, padx="10")
f1_4_ent_EMS = Entry(frame1, width=5)
f1_4_ent_EMS.insert(0, "200")
f1_4_ent_EMS.grid(row=3, column=5, padx="10")
f1_4_lab_slash_2 = Label(frame1, bg="white", text="/")
f1_4_lab_slash_2.grid(row=3, column=6, padx="10")
f1_4_btn_result = Button(frame1, text="합계", command=f1_4_alert)
f1_4_btn_result.grid(row=3, column=7, padx="10")
f1_4_lab_result = Label(frame1, width=20, anchor="w")
f1_4_lab_result.grid(row=3, column=8, padx="10")

f1_5_lab_cost = Label(frame1, bg="white", text="Cost :      ")
f1_5_lab_cost.grid(row=4, column=0, padx="10", pady="5")
f1_5_ent_cost = Entry(frame1, width=7)
f1_5_ent_cost.bind("<Return>", f1_5_alert)
f1_5_ent_cost.grid(row=4, column=1, padx="10")
f1_5_lab_cost_ed = Label(frame1, width=7, bg="gray", anchor="w")
f1_5_lab_cost_ed.grid(row=4, column=2, padx="10")
f1_5_lab_slash_1 = Label(frame1, bg="white", text="/")
f1_5_lab_slash_1.grid(row=4, column=3, padx="10")
f1_5_lab_EMS = Label(frame1, bg="white", text="EMS :")
f1_5_lab_EMS.grid(row=4, column=4, padx="10")
f1_5_ent_EMS = Entry(frame1, width=5)
f1_5_ent_EMS.insert(0, "250")
f1_5_ent_EMS.grid(row=4, column=5, padx="10")
f1_5_lab_slash_2 = Label(frame1, bg="white", text="/")
f1_5_lab_slash_2.grid(row=4, column=6, padx="10")
f1_5_btn_result = Button(frame1, text="합계", command=f1_5_alert)
f1_5_btn_result.grid(row=4, column=7, padx="10")
f1_5_lab_result = Label(frame1, width=20, anchor="w")
f1_5_lab_result.grid(row=4, column=8, padx="10")

f1_6_lab_cost = Label(frame1, bg="white", text="Cost :      ")
f1_6_lab_cost.grid(row=5, column=0, padx="10", pady="5")
f1_6_ent_cost = Entry(frame1, width=7)
f1_6_ent_cost.bind("<Return>", f1_6_alert)
f1_6_ent_cost.grid(row=5, column=1, padx="10")
f1_6_lab_cost_ed = Label(frame1, width=7, bg="gray", anchor="w")
f1_6_lab_cost_ed.grid(row=5, column=2, padx="10")
f1_6_lab_slash_1 = Label(frame1, bg="white", text="/")
f1_6_lab_slash_1.grid(row=5, column=3, padx="10")
f1_6_lab_EMS = Label(frame1, bg="white", text="EMS :")
f1_6_lab_EMS.grid(row=5, column=4, padx="10")
f1_6_ent_EMS = Entry(frame1, width=5)
f1_6_ent_EMS.insert(0, "1000")
f1_6_ent_EMS.grid(row=5, column=5, padx="10")
f1_6_lab_slash_2 = Label(frame1, bg="white", text="/")
f1_6_lab_slash_2.grid(row=5, column=6, padx="10")
f1_6_btn_result = Button(frame1, text="합계", command=f1_6_alert)
f1_6_btn_result.grid(row=5, column=7, padx="10")
f1_6_lab_result = Label(frame1, width=20, anchor="w")
f1_6_lab_result.grid(row=5, column=8, padx="10")


frame2 = LabelFrame(window, text="고가품목", bg="white")
frame2.place(x=10, y=240, width=750, height=125)

# f2_1_lab_cost = Label(frame2, bg="white", text="Cost :      ")
# f2_1_lab_cost.grid(row=0, column=0, padx="10", pady="5")
# f2_1_ent_cost = Entry(frame2, width=7)
# f2_1_ent_cost.bind("<Return>", f2_1_alert)
# f2_1_ent_cost.grid(row=0, column=1, padx="10")
# f2_1_lab_cost_ed = Label(frame2, width=7, bg="gray", anchor="w")
# f2_1_lab_cost_ed.grid(row=0, column=2, padx="10")
# f2_1_lab_slash_1 = Label(frame2, bg="white", text="/")
# f2_1_lab_slash_1.grid(row=0, column=3, padx="10")
# f2_1_lab_EMS = Label(frame2, bg="white", text="EMS :")
# f2_1_lab_EMS.grid(row=0, column=4, padx="10")
# f2_1_ent_EMS = Entry(frame2, width=5)
# f2_1_ent_EMS.insert(0, "150")
# f2_1_ent_EMS.grid(row=0, column=5, padx="10")
# f2_1_lab_slash_2 = Label(frame2, bg="white", text="/")
# f2_1_lab_slash_2.grid(row=0, column=6, padx="10")
# f2_1_btn_result = Button(frame2, text="합계", command=f2_1_alert)
# f2_1_btn_result.grid(row=0, column=7, padx="10")
# f2_1_lab_result = Label(frame2, width=20, anchor="w")
# f2_1_lab_result.grid(row=0, column=8, padx="10")
#
# f2_2_lab_cost = Label(frame2, bg="white", text="Cost :      ")
# f2_2_lab_cost.grid(row=1, column=0, padx="10", pady="5")
# f2_2_ent_cost = Entry(frame2, width=7)
# f2_2_ent_cost.bind("<Return>", f2_2_alert)
# f2_2_ent_cost.grid(row=1, column=1, padx="10")
# f2_2_lab_cost_ed = Label(frame2, width=7, bg="gray", anchor="w")
# f2_2_lab_cost_ed.grid(row=1, column=2, padx="10")
# f2_2_lab_slash_1 = Label(frame2, bg="white", text="/")
# f2_2_lab_slash_1.grid(row=1, column=3, padx="10")
# f2_2_lab_EMS = Label(frame2, bg="white", text="EMS :")
# f2_2_lab_EMS.grid(row=1, column=4, padx="10")
# f2_2_ent_EMS = Entry(frame2, width=5)
# f2_2_ent_EMS.insert(0, "200")
# f2_2_ent_EMS.grid(row=1, column=5, padx="10")
# f2_2_lab_slash_2 = Label(frame2, bg="white", text="/")
# f2_2_lab_slash_2.grid(row=1, column=6, padx="10")
# f2_2_btn_result = Button(frame2, text="합계", command=f2_2_alert)
# f2_2_btn_result.grid(row=1, column=7, padx="10")
# f2_2_lab_result = Label(frame2, width=20, anchor="w")
# f2_2_lab_result.grid(row=1, column=8, padx="10")
#
# f2_3_lab_cost = Label(frame2, bg="white", text="Cost :      ")
# f2_3_lab_cost.grid(row=2, column=0, padx="10", pady="5")
# f2_3_ent_cost = Entry(frame2, width=7)
# f2_3_ent_cost.bind("<Return>", f2_3_alert)
# f2_3_ent_cost.grid(row=2, column=1, padx="10")
# f2_3_lab_cost_ed = Label(frame2, width=7, bg="gray", anchor="w")
# f2_3_lab_cost_ed.grid(row=2, column=2, padx="10")
# f2_3_lab_slash_1 = Label(frame2, bg="white", text="/")
# f2_3_lab_slash_1.grid(row=2, column=3, padx="10")
# f2_3_lab_EMS = Label(frame2, bg="white", text="EMS :")
# f2_3_lab_EMS.grid(row=2, column=4, padx="10")
# f2_3_ent_EMS = Entry(frame2, width=5)
# f2_3_ent_EMS.insert(0, "250")
# f2_3_ent_EMS.grid(row=2, column=5, padx="10")
# f2_3_lab_slash_2 = Label(frame2, bg="white", text="/")
# f2_3_lab_slash_2.grid(row=2, column=6, padx="10")
# f2_3_btn_result = Button(frame2, text="합계", command=f2_3_alert)
# f2_3_btn_result.grid(row=2, column=7, padx="10")
# f2_3_lab_result = Label(frame2, width=20, anchor="w")
# f2_3_lab_result.grid(row=2, column=8, padx="10")


frame3 = LabelFrame(window, text="겨울패딩", bg="white")
frame3.place(x=10, y=365, width=750, height=155)

f3_1_lab_cost = Label(frame3, bg="white", text="경량패딩 :")
f3_1_lab_cost.grid(row=0, column=0, padx="10", pady="5")
f3_1_ent_cost = Entry(frame3, width=7)
f3_1_ent_cost.bind("<Return>", f3_1_alert)
f3_1_ent_cost.grid(row=0, column=1, padx="10")
f3_1_lab_cost_ed = Label(frame3, width=7, bg="gray", anchor="w")
f3_1_lab_cost_ed.grid(row=0, column=2, padx="10")
f3_1_lab_slash_1 = Label(frame3, bg="white", text="/")
f3_1_lab_slash_1.grid(row=0, column=3, padx="10")
f3_1_lab_EMS = Label(frame3, bg="white", text="EMS :")
f3_1_lab_EMS.grid(row=0, column=4, padx="10")
f3_1_ent_EMS = Entry(frame3, width=5)
f3_1_ent_EMS.insert(0, "200")
f3_1_ent_EMS.grid(row=0, column=5, padx="10")
f3_1_lab_slash_2 = Label(frame3, bg="white", text="/")
f3_1_lab_slash_2.grid(row=0, column=6, padx="10")
f3_1_btn_result = Button(frame3, text="합계", command=f3_1_alert)
f3_1_btn_result.grid(row=0, column=7, padx="10")
f3_1_lab_result = Label(frame3, width=20, anchor="w")
f3_1_lab_result.grid(row=0, column=8, padx="10")

f3_2_lab_cost = Label(frame3, bg="white", text="패딩조끼 :")
f3_2_lab_cost.grid(row=1, column=0, padx="10", pady="5")
f3_2_ent_cost = Entry(frame3, width=7)
f3_2_ent_cost.bind("<Return>", f3_2_alert)
f3_2_ent_cost.grid(row=1, column=1, padx="10")
f3_2_lab_cost_ed = Label(frame3, width=7, bg="gray", anchor="w")
f3_2_lab_cost_ed.grid(row=1, column=2, padx="10")
f3_2_lab_slash_1 = Label(frame3, bg="white", text="/")
f3_2_lab_slash_1.grid(row=1, column=3, padx="10")
f3_2_lab_EMS = Label(frame3, bg="white", text="EMS :")
f3_2_lab_EMS.grid(row=1, column=4, padx="10")
f3_2_ent_EMS = Entry(frame3, width=5)
f3_2_ent_EMS.insert(0, "200")
f3_2_ent_EMS.grid(row=1, column=5, padx="10")
f3_2_lab_slash_2 = Label(frame3, bg="white", text="/")
f3_2_lab_slash_2.grid(row=1, column=6, padx="10")
f3_2_btn_result = Button(frame3, text="합계", command=f3_2_alert)
f3_2_btn_result.grid(row=1, column=7, padx="10")
f3_2_lab_result = Label(frame3, width=20, anchor="w")
f3_2_lab_result.grid(row=1, column=8, padx="10")

f3_3_lab_cost = Label(frame3, bg="white", text="일반패숏 :")
f3_3_lab_cost.grid(row=2, column=0, padx="10", pady="5")
f3_3_ent_cost = Entry(frame3, width=7)
f3_3_ent_cost.bind("<Return>", f3_3_alert)
f3_3_ent_cost.grid(row=2, column=1, padx="10")
f3_3_lab_cost_ed = Label(frame3, width=7, bg="gray", anchor="w")
f3_3_lab_cost_ed.grid(row=2, column=2, padx="10")
f3_3_lab_slash_1 = Label(frame3, bg="white", text="/")
f3_3_lab_slash_1.grid(row=2, column=3, padx="10")
f3_3_lab_EMS = Label(frame3, bg="white", text="EMS :")
f3_3_lab_EMS.grid(row=2, column=4, padx="10")
f3_3_ent_EMS = Entry(frame3, width=5)
f3_3_ent_EMS.insert(0, "200")
f3_3_ent_EMS.grid(row=2, column=5, padx="10")
f3_3_lab_slash_2 = Label(frame3, bg="white", text="/")
f3_3_lab_slash_2.grid(row=2, column=6, padx="10")
f3_3_btn_result = Button(frame3, text="합계", command=f3_3_alert)
f3_3_btn_result.grid(row=2, column=7, padx="10")
f3_3_lab_result = Label(frame3, width=20, anchor="w")
f3_3_lab_result.grid(row=2, column=8, padx="10")

f3_4_lab_cost = Label(frame3, bg="white", text="일반패롱 :")
f3_4_lab_cost.grid(row=3, column=0, padx="10", pady="5")
f3_4_ent_cost = Entry(frame3, width=7)
f3_4_ent_cost.bind("<Return>", f3_4_alert)
f3_4_ent_cost.grid(row=3, column=1, padx="10")
f3_4_lab_cost_ed = Label(frame3, width=7, bg="gray", anchor="w")
f3_4_lab_cost_ed.grid(row=3, column=2, padx="10")
f3_4_lab_slash_1 = Label(frame3, bg="white", text="/")
f3_4_lab_slash_1.grid(row=3, column=3, padx="10")
f3_4_lab_EMS = Label(frame3, bg="white", text="EMS :")
f3_4_lab_EMS.grid(row=3, column=4, padx="10")
f3_4_ent_EMS = Entry(frame3, width=5)
f3_4_ent_EMS.insert(0, "250")
f3_4_ent_EMS.grid(row=3, column=5, padx="10")
f3_4_lab_slash_2 = Label(frame3, bg="white", text="/")
f3_4_lab_slash_2.grid(row=3, column=6, padx="10")
f3_4_btn_result = Button(frame3, text="합계", command=f3_4_alert)
f3_4_btn_result.grid(row=3, column=7, padx="10")
f3_4_lab_result = Label(frame3, width=20, anchor="w")
f3_4_lab_result.grid(row=3, column=8, padx="10")


frame4 = LabelFrame(window, text="메모", bg="white")
frame4.place(x=10, y=520, width=750, height=400)

f4_memo_btn_1 = Button(window, text="저장", bg="yellow", command=f4_memo_write)
f4_memo_btn_1.place(x=60, y=520, height=20)

f4_memo_text_1 = Text(frame4, width=90, height=22)
f = open("data.txt", "r")
f4_memo_text_1.insert(1.0, f.read())
f.close()
f4_memo_text_1.place(x=10, y=10)


window.mainloop()
